### ISSUE TITLE
Guarded Transition for not changing State

### ISSUE THREAD

**Issue by tuncatunc** [oxo42/stateless4j#41]
When I configure a state transition with permitIf and the guard function doesn't allow the transition
I'm getting following exception. However I except the state unchanged.

``` java
        smCfg.configure(State.STATE_0)
            .permitIf(Event.TC_setup, State.STATE_1, new FuncBoolean()
            {

                @Override
                public boolean call()
                {
                    boolean result = hdlcIo.setup(); 
                    return result;
                }
            })
```

``` java
java.lang.IllegalStateException: No valid leaving transitions are permitted from state 'STATE_0' for trigger 'TC_setup'. Consider ignoring the trigger.
    at com.github.oxo42.stateless4j.StateMachine$1.doIt(StateMachine.java:30)
    at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:196)
    at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:133)
    at com.ayes.atmgw.service.ph.fde.FdeStateMachine.setup(FdeStateMachine.java:472)
    at com.ayes.atmgw.tests.TestFdeStateMachine.test02_STATE0_TC_Setup_fails(TestFdeStateMachine.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by rv7akro** [comment]
I am encountering the exact same problem. See below ...

Exception in thread "EventHandler-43680156-e573-48c5-966c-7f8ad087f066" java.lang.IllegalStateException: No valid leaving transitions are permitted from state 'IDLE' for trigger 'class com.cisco.swag.whisper.events.system.DependenciesReady'. Consider ignoring the trigger.
	at com.github.oxo42.stateless4j.StateMachine$1.doIt(StateMachine.java:30)
	at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:188)
	at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:125)
	at com.cisco.swag.whisper.plugin.AgentPlugin$1.handleEvent(AgentPlugin.java:176)
	at com.cisco.swag.whisper.events.EventQueue$EventHandler.handleEvent(EventQueue.java:153)
	at com.cisco.swag.whisper.events.EventQueue$EventHandler.run(EventQueue.java:126)
	at java.lang.Thread.run(Thread.java:724)

Can we get some more insight on how to successfully utilize guard functions?

**Comment by Ktar5** [comment]
This is obviously a /very/ lame way of working around this issue. So I'll figure out a way to work this into the code so that users no longer run into this. Thanks for submitting and thanks for helping out @rv7akro

**Comment by Ktar5** [comment]
Turns out that if we implement this any other way, we end up removing some portion of the functionality. I'll update the error message to reflect what I've found.
